name: Nightly Test run (Jahia SN)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  integration-tests:
    uses:  Jahia/jahia-modules-action/.github/workflows/integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: jahia/jahia-ee-dev:8-SNAPSHOT
      module_id: jahia-csrf-guard
      testrail_project: Jahia CSRF Guard module
      pagerduty_incident_service: jahia-csrf-guard-JahiaSN
      provisioning_manifest: provisioning-manifest-snapshot.yml
      artifact_prefix: jahia-csrf-guard
      module_branch: ${{ github.ref }}
